window.MTPresenceArchiveData = {
  ratioProfiles: [
    { label: "1:1", ratio: 1 / 1 },
    { label: "4:3", ratio: 4 / 3 },
    { label: "4:5", ratio: 4 / 5 },
    { label: "2:3", ratio: 2 / 3 },
    { label: "3:2", ratio: 3 / 2 },
    { label: "16:9", ratio: 16 / 9 },
    { label: "Panorama", ratio: 2 / 1 },
  ],
  sampleItems: [
    {
      id: "sample-1",
      title: "Square Shadow Field",
      src: "assets/archive/abstract-square-01.jpg",
      width: 1600,
      height: 1600,
      type: "Abstract",
      ratio: "1:1",
      source: "Local sample",
    },
    {
      id: "sample-2",
      title: "Vertical Light Pattern",
      src: "assets/archive/abstract-4x5-01.jpg",
      width: 1600,
      height: 2000,
      type: "Abstract",
      ratio: "4:5",
      source: "Local sample",
    },
    {
      id: "sample-26",
      title: "Balanced Abstract Field",
      src: "assets/archive/abstract-4x3-01.jpg",
      width: 2000,
      height: 1500,
      type: "Abstract",
      ratio: "4:3",
      source: "Local sample",
    },
    {
      id: "sample-27",
      title: "Concrete Four Thirds Study",
      src: "assets/archive/concrete-4x3-01.jpg",
      width: 2000,
      height: 1500,
      type: "Concrete",
      ratio: "4:3",
      source: "Local sample",
    },
    {
      id: "sample-3",
      title: "Concrete Valley",
      src: "assets/archive/concrete-2x3-01.jpg",
      width: 1600,
      height: 2400,
      type: "Concrete",
      ratio: "2:3",
      source: "Local sample",
    },
    {
      id: "sample-4",
      title: "Architectural Plane",
      src: "assets/archive/concrete-3x2-01.jpg",
      width: 2400,
      height: 1600,
      type: "Concrete",
      ratio: "3:2",
      source: "Local sample",
    },
    {
      id: "sample-5",
      title: "Wide Weather",
      src: "assets/archive/concrete-16x9-01.jpg",
      width: 1920,
      height: 1080,
      type: "Concrete",
      ratio: "16:9",
      source: "Local sample",
    },
    {
      id: "sample-6",
      title: "Panorama Surface",
      src: "assets/archive/abstract-panorama-01.jpg",
      width: 2400,
      height: 1200,
      type: "Abstract",
      ratio: "Panorama",
      source: "Local sample",
    },
    {
      id: "sample-7",
      title: "Minimal Stone Detail",
      src: "assets/archive/abstract-4x5-02.jpg",
      width: 1600,
      height: 2000,
      type: "Abstract",
      ratio: "4:5",
      source: "Local sample",
    },
    {
      id: "sample-8",
      title: "Identifiable Coast",
      src: "assets/archive/concrete-2x3-02.jpg",
      width: 1600,
      height: 2400,
      type: "Concrete",
      ratio: "2:3",
      source: "Local sample",
    },
    {
      id: "sample-9",
      title: "Horizontal Silence",
      src: "assets/archive/abstract-3x2-01.jpg",
      width: 2400,
      height: 1600,
      type: "Abstract",
      ratio: "3:2",
      source: "Local sample",
    },
    {
      id: "sample-10",
      title: "Color Object Study",
      src: "assets/archive/concrete-square-01.jpg",
      width: 1600,
      height: 1600,
      type: "Concrete",
      ratio: "1:1",
      source: "Local sample",
    },
    {
      id: "sample-11",
      title: "Abstract Wide Interval",
      src: "assets/archive/abstract-16x9-01.jpg",
      width: 1920,
      height: 1080,
      type: "Abstract",
      ratio: "16:9",
      source: "Local sample",
    },
    {
      id: "sample-12",
      title: "Concrete Animal Study",
      src: "assets/archive/concrete-4x5-01.jpg",
      width: 1600,
      height: 2000,
      type: "Concrete",
      ratio: "4:5",
      source: "Local sample",
    },
    {
      id: "sample-13",
      title: "Concrete Panorama",
      src: "assets/archive/concrete-panorama-01.jpg",
      width: 2400,
      height: 1200,
      type: "Concrete",
      ratio: "Panorama",
      source: "Local sample",
    },
    {
      id: "sample-14",
      title: "Square Abstract Interval",
      src: "assets/archive/abstract-square-02.jpg",
      width: 1600,
      height: 1600,
      type: "Abstract",
      ratio: "1:1",
      source: "Local sample",
    },
    {
      id: "sample-15",
      title: "Concrete Square Study",
      src: "assets/archive/concrete-square-02.jpg",
      width: 1600,
      height: 1600,
      type: "Concrete",
      ratio: "1:1",
      source: "Local sample",
    },
    {
      id: "sample-16",
      title: "Vertical Abstract Surface",
      src: "assets/archive/abstract-4x5-03.jpg",
      width: 1600,
      height: 2000,
      type: "Abstract",
      ratio: "4:5",
      source: "Local sample",
    },
    {
      id: "sample-17",
      title: "Concrete Vertical Field",
      src: "assets/archive/concrete-4x5-02.jpg",
      width: 1600,
      height: 2000,
      type: "Concrete",
      ratio: "4:5",
      source: "Local sample",
    },
    {
      id: "sample-18",
      title: "Tall Abstract Study",
      src: "assets/archive/abstract-2x3-01.jpg",
      width: 1600,
      height: 2400,
      type: "Abstract",
      ratio: "2:3",
      source: "Local sample",
    },
    {
      id: "sample-19",
      title: "Tall Concrete Study",
      src: "assets/archive/concrete-2x3-03.jpg",
      width: 1600,
      height: 2400,
      type: "Concrete",
      ratio: "2:3",
      source: "Local sample",
    },
    {
      id: "sample-20",
      title: "Abstract Horizontal Plane",
      src: "assets/archive/abstract-3x2-02.jpg",
      width: 2400,
      height: 1600,
      type: "Abstract",
      ratio: "3:2",
      source: "Local sample",
    },
    {
      id: "sample-21",
      title: "Concrete Horizontal Plane",
      src: "assets/archive/concrete-3x2-02.jpg",
      width: 2400,
      height: 1600,
      type: "Concrete",
      ratio: "3:2",
      source: "Local sample",
    },
    {
      id: "sample-22",
      title: "Abstract Wide Field",
      src: "assets/archive/abstract-16x9-02.jpg",
      width: 1920,
      height: 1080,
      type: "Abstract",
      ratio: "16:9",
      source: "Local sample",
    },
    {
      id: "sample-23",
      title: "Concrete Wide Field",
      src: "assets/archive/concrete-16x9-02.jpg",
      width: 1920,
      height: 1080,
      type: "Concrete",
      ratio: "16:9",
      source: "Local sample",
    },
    {
      id: "sample-24",
      title: "Abstract Long Horizon",
      src: "assets/archive/abstract-panorama-02.jpg",
      width: 2400,
      height: 1200,
      type: "Abstract",
      ratio: "Panorama",
      source: "Local sample",
    },
    {
      id: "sample-25",
      title: "Concrete Long Horizon",
      src: "assets/archive/concrete-panorama-02.jpg",
      width: 2400,
      height: 1200,
      type: "Concrete",
      ratio: "Panorama",
      source: "Local sample",
    },
  ],
};
